# Quire PDF. The macOS app lives in macos/; its project is generated
# from macos/project.yml by xcodegen.
#
#   make ci     everything this machine can check
.DEFAULT_GOAL := help

.PHONY: help
help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | \
	  awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

.PHONY: ci
ci: ci-version macos ## Everything checkable on this machine

.PHONY: ci-version
ci-version: ## The version derivation, which the app's test suite cannot reach
	@./scripts/version.test.sh

.PHONY: icon
icon: ## Export every icon from branding/logo.svg (needs Chrome)
	./branding/export.sh

.PHONY: macos-project
macos-project: ## Regenerate the Xcode project from macos/project.yml
	cd macos && xcodegen generate

.PHONY: macos-version
macos-version: ## Stamp the marketing version and the build number
	@# Two different numbers. The marketing version is derived from VERSION and
	@# the history, and its patch resets when the minor is bumped. The build
	@# number is the total commit count and must never reset: the App Store
	@# refuses an upload whose build number does not exceed the last one.
	@# Each step must stop the recipe on failure: without the `&&`s a failed
	@# version.sh still writes the file, with an empty MARKETING_VERSION that
	@# overrides Base.xcconfig's fallback and exits 0.
	@version="$$(./scripts/version.sh)" && \
	  build="$$(git rev-list --count HEAD)" && \
	  printf '// Generated by `make macos-version`. Do not edit or commit.\nMARKETING_VERSION = %s\nCURRENT_PROJECT_VERSION = %s\n' \
	    "$$version" "$$build" > macos/Config/Version.xcconfig && \
	  echo "version: $$version   build: $$build"

.PHONY: macos
macos: ## Build and test the macOS app
	cd macos && xcodebuild -project QuirePDF.xcodeproj -scheme QuirePDF \
	  -destination 'platform=macOS' test
